App/views/camera.py
from flask import Flask, Blueprint, render_template, session, redirect, url_for, request, Response
from App.models import db, Order

camerablue = Blueprint('camerablue', __name__)

@camerablue.route('/camera', methods=['POST', 'GET'])
def camera():
    return 'camera'

App/views/surveillance.py
from flask import Flask, Blueprint, render_template, session, redirect, url_for, request, Response, jsonify
from App.models import db, Order
import json
import datetime
from App.models import db, User, Video

surveillanceblue = Blueprint('surveillanceblue', __name__)
camerautl = None
global_frame = None
SAVE_PATH = "/home/pi/Videos/Test"  # will be created if doesnt exist
from App.tools.camerautl import VideoCamera


@surveillanceblue.route('/surveillance/camera', methods=['POST', 'GET'])
def camera():
    return render_template('surveillance/camera.html')


@surveillanceblue.route('/surveillance/managefacedata', methods=['POST', 'GET'])
def manage_face_data():
    return render_template('surveillance/managefacedata.html')


def gen():
    global camerautl
    global global_frame

    if camerautl is None:
        camerautl = VideoCamera()

    while True:
        frame = camerautl.get_frame()

        if frame is not None:
            global_frame = frame
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
        else:
            yield (b'--frame\r\n'
                   b'Content-Type: image/jpeg\r\n\r\n' + global_frame + b'\r\n\r\n')


@surveillanceblue.route('/surveillance/streaming')
def streaming():
    return Response(gen(),
                    mimetype='multipart/x-mixed-replace; boundary=frame')


@surveillanceblue.route('/surveillance/recordstatus', methods=['POST'])
def record_status():
    global camerautl
    if camerautl is None:
        camerautl = VideoCamera()

    json = request.get_json()

    status = json['status']

    if status == "true":
        camerautl.start_record()
        return jsonify(result="开始")
    else:
        save_path = camerautl.stop_record()
        item = session.get('user')
        video = Video()
        video.videoid = video.query.count() + 1
        video.videoname = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
        video.savepath = save_path
        if item is not None:
            userid = item.get('id')
            video.userid = userid
        db.session.add(video)
        db.session.commit()
        return jsonify(result="停止", save_path=save_path)


@surveillanceblue.route('/surveillance/downloadvideo', methods=['POST', 'GET'])
def download_video():
    item = session.get('user')
    userid = item.get('id')
    videos = Video.query.filter(Video.userid == userid).all()
    print(videos)
    return render_template('/surveillance/downloadvideo.html', videos=videos)


@surveillanceblue.route('/surveillance/faceupload', methods=['POST', 'GET'])
def upload_face():
    msg = ''
    if request.method == 'POST':
        file = request.files['file']
        if file:
            filename = file.filename
            # creating a folder if there is no one yet
            # saving file with new name in exact folder
            upload_folder = 'App/static/faces/'
            file.save(upload_folder + filename)
            session['msg'] = '成功'
            msg = '成功'
        else:
            session['msg'] = '失败'
            msg = '失败'
    return render_template('/surveillance/uploadfacesuccess.html', msg=msg)

App/templates/surveillance/camera.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/dist/css/bootstrap.min.css') }}">
    <script src="{{ url_for('static',filename='jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='bootstrap/dist/js/bootstrap.min.js') }}"></script>
</head>

<title>Camera</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

<body>
<div class="container">
    <!-- Content here -->
    <center><h1>摄像头</h1></center>
    <div class="top">
        <div class="recorder" id="recorder" align="center">
            <button id="record" class="btn">开始录像</button>
            <button id="stop" class="btn">停止录像</button>
            <a id="download"></a>
            <script type="text/javascript" src="{{ url_for('static', filename='js/recorder.js') }}"></script>
        </div>
    </div>
    <p class="alert alert-success" style="text-align: center;" id="msg"></p>
    <div style="text-align: center;"><img width="640" height="480" id="video"
                                          src="{{ url_for('surveillanceblue.streaming') }}"></div>
</div>

</body>
</html>

App/templates/surveillance/downloadvideo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Video Download</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/dist/css/tablecloth.css') }}">
    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/dist/css/bootstrap.min.css') }}">
    <script type="text/javascript" src="../../static/js/tablecloth.js"></script>
</head>
<body>
<div class="container">
    <!-- Content here -->
    <h1>Video</h1>
    <table class="table table-striped table-sm" cellspacing="0" cellpadding="0">
        <tr>
            <td>Id</td>
            <th>Name</th>
            <th>Download</th>
        </tr>
        {% for video in videos %}
            <tr>
                <td>{{ video.videoid }}</td>
                <td>{{ video.videoname }}</td>
                <td><a href={{ video.savepath }}>Download</a></td>
            </tr>
        {% endfor %}


    </table>
</div>
</body>
</html>

App/templates/surveillance/managefacedata.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/dist/css/bootstrap.min.css') }}">
    <script src="{{ url_for('static',filename='jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='bootstrap/dist/js/bootstrap.min.js') }}"></script>
</head>
<body>
<div class="container">
    <!-- Content here -->
    <h2>上传宿舍成员照片，文件名为名字。</h2>
    <form action="/surveillance/faceupload" method=post enctype=multipart/form-data>
        <div class="input-group">
            <label class="input-group-btn">
        <span class="btn btn-primary">
            Choose File<input type=file name=file>
        </span>
            </label>
            <input class="btn btn-primary" type=submit value=上传>
        </div>
    </form>
</div>
<script>
    $(document).on('change', ':file', function () {
        var input = $(this),
            numFiles = input.get(0).files ? input.get(0).files.length : 1,
            label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
        input.parent().parent().next(':text').val(label);
    });
</script>
</body>
</html>

App/templates/surveillance/uploadfacesuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <!-- Content here -->
    <h>保存文件{{ msg }}</h>
</div>
</body>
</html>